### ISSUE TITLE
brv_we14py.py: ValueError: invalid literal for int() with base 10: 'N'

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/serval#12]
On one Ubuntu system the following problem occured with the test example:

```
serval gj699 data/HARPS/gj699/ -inst HARPS -targ gj699
['/home/astropc/mzechmeister/serval//src/serval.py', 'gj699', 'data/HARPS/gj699/', '-inst', 'HARPS', '-targ', 'gj699']

SERVAL - SpEctrum Radial Velocity AnaLyser (2018-08-27)
     by Mathias Zechmeister

start time: 2018-10-23 10:27:32 Tue
targ.py: restoring 'gj699' from gj699/gj699.targ.cvs
 using sa= 4.53457382248 m/s/yr ra= (17.0, 57.0, 48.4997994034) de= (4.0, 41.0, 36.111354228) pmra= -802.803 pmde= 10362.542
data/HARPS/gj699/
tpl=None pmin=300 iset=slice(None, None, None) omin=10 omax=70
maskfile /home/astropc/mzechmeister/serval/lib/telluric_mask_atlas_short.dat
using telluric mask:  /home/astropc/mzechmeister/serval/lib/telluric_mask_atlas_short.dat
    # inst_mode   timeid                          OBJECT    BJD        SN  DRSBERV  DRSdrift flag calmode
  1/10 read_harps: 2007-07-17T04:55:15.834 Gl699 2454298.71451 75.1 -11.1230643233 0.0 0 OBJ,SKY
Traceback (most recent call last):
  File "/home/astropc/mzechmeister/serval//src/serval.py", line 2339, in <module>
    sys.exit(serval())
  File "/home/astropc/mzechmeister/serval//src/serval.py", line 942, in serval
    sp = Spectrum(filename, inst=inst, pfits=2 if 'HARP' in inst else True, drs=drs, fib=fib, targ=targ, verb=True)
  File "/home/astropc/mzechmeister/serval/src/read_spec.py", line 151, in __init__
    self.bjd, self.berv = brv_we14py.bjdbrv(jd_utc=jd_utc[0], ra=ra, dec=de, obsname=obsname, pmra=targ.pmra, pmdec=targ.pmde, parallax=0., rv=0., zmeas=[0])
  File "/home/astropc/mzechmeister/serval/src/brv_we14py.py", line 60, in bjdbrv
    ltt_bary = JDUTC.light_travel_time(targ, location=loc)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/time/core.py", line 683, in light_travel_time
    gcrs_coo = itrs.transform_to(GCRS(obstime=self))
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/coordinates/baseframe.py", line 934, in transform_to
    return trans(self, new_frame)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 1314, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/coordinates/transformations.py", line 914, in __call__
    return supcall(fromcoord, toframe)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 89, in itrs_to_cirs
    pmat = cirs_to_itrs_mat(itrs_coo.obstime)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 33, in cirs_to_itrs_mat
    xp, yp = get_polar_motion(time)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/utils.py", line 43, in get_polar_motion
    xp, yp, status = iers.IERS_Auto.open().pm_xy(time, return_status=True)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 583, in open
    cls.iers_table = cls.read(file=filename)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 455, in read
    table = cls._combine_a_b_columns(iers_a)
  File "/home/astropc/.local/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 417, in _combine_a_b_columns
    is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
  File "/home/astropc/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 3016, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "/home/astropc/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 476, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: invalid literal for int() with base 10: 'N'
```

**Comment by mzechmeister** [comment]
Compared with a working installation the same parameters seem to be passed.
So the problem might arise from barycorrpy  or astropy version.

A quick alternative is to use another barycentric correction code, e.g. `-brvref MH`.

**Comment by mzechmeister** [comment]
This was a problem on Douglas' computer. Unclear, whether the problem still exist. Thus, I'm closing this issue.
