### ISSUE TITLE
targ.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by mzechmeister** [mzechmeister/serval#13]
Requests with gj9xxx results in
```
targ.py: restoring 'gj9222' from test/test.targ.cvs
targ.py: requesting simbad for 'gj9222'
storing in test/test.targ.cvs
Traceback (most recent call last):
  File "/home/raid0/zechmeister/bin/serval", line 2342, in <module>
    sys.exit(serval())
  File "/home/raid0/zechmeister/bin/serval", line 779, in serval
    targ = Targ(targ.name, targrade, targpm, plx=targplx, rv=targrv, cvs=obj+'/'+obj+'.targ.cvs')
  File "/home/astro133/zechmeister/carmenes/serval/src/targ.py", line 69, in __init__
    self.assignAttr(self.line)
  File "/home/astro133/zechmeister/carmenes/serval/src/targ.py", line 92, in assignAttr
    self.pmra = float(line[6].replace("~","0."))             # pma = -3775.75
IndexError: list index out of range
```

**Comment by mzechmeister** [comment]
The content of the request is
```
(Pdb) self.line
'!! A problem occured with the script file. It may be too large (max: 31457280 bytes) null/null/null\n\n'
```
which can reproduced with
```
import urllib, urllib2
query = urllib.quote("\n".join([
      'output script=off',
      'output console=off',
      'format object form1 "%OBJECT;%IDLIST(1);%COO(A D);%PM(A D [E]);%PLX;%RV"',
      'query gj9222']))
urllib2.urlopen('http://simbad.u-strasbg.fr/simbad/sim-script', 'submit=submit+script&script='+query).read()
```

**Comment by mzechmeister** [comment]
This is also the output of
http://simbad.u-strasbg.fr/simbad/sim-script
The problem is not only for gj9xxxx but also for all stars. Seems like the server is down. Requests are forwarded to the US mirror. The interactive request form is at
http://simbad.cfa.harvard.edu/simbad/sim-fscript
When using the new access point, it works
'http://simbad.cfa.harvard.edu/simbad/sim-script'

**Comment by mzechmeister** [comment]
The master also works from bash
```bash
wget -q -O - 'http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=output+script%3Doff%0D%0Aoutput+console%3Doff%0D%0Aformat+object+form1+%22%25OBJECT+%3A+%25IDLIST%281%29+%3A+%25COO%28A+D%29+%25PM%28A+D+[E]%29+%25PLX\n%22%0D%0Aquery+gj9222'
```
Probably, it is redirected to the right page.

**Comment by mzechmeister** [comment]
`geturl()` show that the final url is resolved
```python
>>> urllib2.urlopen('http://simbad.u-strasbg.fr/simbad/sim-script').geturl()
'http://simbad.cfa.harvard.edu/simbad/sim-script'
```
But it is not clear, why the final url is not applied.
