### ISSUE TITLE
"SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?" error message for SOPHIE spectra

### ISSUE THREAD

**Issue by AndreOKovacs** [mzechmeister/serval#69]
Hello,

I'm trying to process some archived SOPHIE spectra (only public data from the data archive) and I'm getting the following error message:
```
Traceback (most recent call last):
  File "/content/serval/src/serval.py", line 2569, in <module>
    inst = importlib.import_module('inst_'+inst)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/serval/src/inst_SOPHIE.py", line 104
    print 'WARNING: proprietary data, dates are rounded.'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
It seems that indeed there're missing parentheses in the call to print(), but I would like to understand the reason why it's complaining about the data being proprietary.
Should I just ignore this warning?

Thanks,
Andre

**Comment by mzechmeister** [comment]
Sorry, for replying so late. I overlooked the ticket.
The inst file for SOPHIE was still for python 2. I fixed it in 579e2bd.

Note also that it seems that the wavemap of SOPHIE is already drift corrected (still waiting for confirmation).
In this case the uncorrected RVs should be used (`RV` instead of `RVc`).

If it works now for you, I will close the ticket.
